name: CI

on:
  push:
    branches:
      - main
      - renovate/**
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  merge_group:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ${{ vars.RUNNER || 'ubuntu-latest' }}
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run tests
        run: make test
