name: CI

on:
  push:
    branches:
      - main
      - renovate/**
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  merge_group:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ${{ vars.RUNNER || 'ubuntu-latest' }}
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set GitHub ENV variables
        shell: bash
        run: |
          echo "GO_VERSION=$( (grep -m1 '^toolchain go' go.mod || grep -m1 '^go ' go.mod) | sed -nE 's/.*go[[:space:]]*//p')" >> $GITHUB_ENV
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run tests
        run: make test
